### ISSUE TITLE
[事件][安全]车厢 一直在尝试选择不能选的选项

### ISSUE THREAD

**Issue by Victor2333** [sMythicalBird/ZenlessZoneZero-Auto#88]
```yaml
#config.yaml
#ZoneMap = {
#    1: {
#        "name": "旧都列车",
#        "level": {1: "外围", 2: "前线", 3: "内部", 4: "腹地", 5: "核心"},
#    },
#    2: {
#        "name": "施工废墟",
#        "level": {1: "前线", 2: "内部", 3: "腹地", 4: "核心"},
#    },
#}

# 模型训练集大部分来自旧都列车，脚本刷图目前旧都列车最稳定，其他图bug会比较多，刷零号业绩旧都列车前线最快，练度够可以直接刷前线
targetMap:
    level: 2 # 默认等级 1: 外围
    zone: 2 # 默认区域 1: 旧都列车
modeSelect: 4 # 模式选择 1: 全通关  2: 刷零号业绩  3：零号银行  4：零号银行零号业绩一起
maxFightTime: 300 # 最大战斗时间，单场战斗时间默认为150s，超过150s会重开(部分战斗场景需要跑图，目前还没进行相关处理，遇到这种情况会退掉重开)
maxMapTime: 1500 # 在地图内最大时间默认为900s，超过最大时间未通关地图会重开
hasBoom: True # 是否解锁炸弹
useGpu: True # 是否使用GPU，默认True, 使用GPU会加速模型训练,如果改为False，会强制使用CPU进行OCR识别
selBuff: ["冻结", "暴击", "决斗", "闪避"] # 鸣辉选择
characters: ["艾莲", "安比", "苍角", "莱卡恩", "朱鸢", "妮可"] # 角色选择，用于载入对应角色战斗模块

```
![image](https://github.com/user-attachments/assets/79dec710-5acf-48a7-8f3d-9a28087e99ac)

2024-07-31 09:15:59.970 | DEBUG    | utils.task:__call__:326 - 进入副本次数：1 当前页面：选项_紫色风险
2024-07-31 09:16:01.654 | DEBUG    | utils.task:__call__:326 - 进入副本次数：1 当前页面：选项_紫色风险
2024-07-31 09:16:03.328 | DEBUG    | utils.task:__call__:326 - 进入副本次数：1 当前页面：选项_紫色风险
2024-07-31 09:16:05.048 | DEBUG    | utils.task:__call__:326 - 进入副本次数：1 当前页面：选项_紫色风险
2024-07-31 09:16:06.725 | DEBUG    | utils.task:__call__:326 - 进入副本次数：1 当前页面：选项_紫色风险
2024-07-31 09:16:08.467 | DEBUG    | utils.task:__call__:326 - 进入副本次数：1 当前页面：选项_紫色风险
2024-07-31 09:16:10.154 | DEBUG    | utils.task:__call__:326 - 进入副本次数：1 当前页面：选项_紫色风险
2024-07-31 09:16:11.869 | DEBUG    | utils.task:__call__:326 - 进入副本次数：1 当前页面：选项_紫色风险
2024-07-31 09:16:13.562 | DEBUG    | utils.task:__call__:326 - 进入副本次数：1 当前页面：选项_紫色风险
2024-07-31 09:16:15.293 | DEBUG    | utils.task:__call__:326 - 进入副本次数：1 当前页面：选项_紫色风险
2024-07-31 09:16:16.977 | DEBUG    | utils.task:__call__:326 - 进入副本次数：1 当前页面：选项_紫色风险
